server.port=8083
spring.kafka.consumer.group-id=storage-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8085}
spring.kafka.consumer.properties.specific.avro.reader=true
aws.endpoint.localstack=http://localhost:4566
aws.access-key=test
aws.secret-key=test
aws.s3.bucket-name=maritime-data
aws.dynamodb.table-name=vessel-risk